[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-yaml"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
entry = "cargo fmt --all -- --check"
language = "system"
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
entry = "cargo clippy --all-targets --all-features --workspace -- -D warnings"
language = "system"
pass_filenames = false

[[repos.hooks]]
id = "cargo-test"
name = "cargo test"
entry = "cargo test --all-features --workspace"
language = "system"
pass_filenames = false
stages = ["pre-push"]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.1"

[[repos.hooks]]
id = "gitleaks"